### ISSUE TITLE
Remove some styles

### ISSUE THREAD

**Issue by mrmartineau** [tmwagency/kickoff#51]
I would like to remove a few styles from Kickoff. Horizontal definition lists, some nav list styles and some other things.. I don't think they're useful to Kickoff's core.. do you agree @ashleynolan @nicbell? 

Here's the sauce:

## Horizontal Definition list
```scss
.dl-horizontal {
	@include clearfix;

	dt {
		@include text-overflow();
		float: left;
		clear: left;
		width: 220px;
		text-align: right;
	}

	dd {
		margin-left: 240px;
	}
}
```

## Nav styles
We could keep `.unstyled` but remove `nav ul` & `nav ol`...
```scss
/**
 * Unstyled lists
 */
.unstyled,
nav ul, nav ol {
	margin: 0;
	padding: 0;
	list-style: none;
	list-style-image: none;
}
```

# Blockquote
```scss
/**
 * Blockquotes
 */
blockquote {
	padding-left: 10px;
	margin: $baseline;
	border-left: 4px solid lighten(#000, 80%);

	p {
		margin-bottom: 0;
		@include font-size($type-base);
		font-weight: 300;
	}

	small {
		display: block;
		color: lighten(#000, 70%);

		&:before {
			content: '\2014 \00A0';
		}
	}
}

// Quotes
q,
blockquote {
	&:before,
	&:after {
		content: "";
	}
}
```

## Address
```scss
// Addresses
address {
	display: block;
	margin-bottom: $baseline;
	font-style: normal;
}
```

## Close Button
```scss
/**
 * Close Button: for lightboxes etc
 */
.btnClose {
	position: absolute;
	right: 20px;
	top: 20px;

	display: block;
	height: 20px;
	width: 20px;
	line-height: 17px;

	background: #000;
	color: $color-primary;
	text-align: center;
	border-radius: 5px;
	cursor: pointer;
	user-select: none;

	&:hover {
		color: #fff;
		border-radius: 50px;
	}
}
```

**Comment by ashleynolan** [comment]
Definitely agree with removing the close button, address, and horizontal dl styling.  Agree with keeping the unstyled list class and getting rid of the nav ul/ol selector too – can simply put the unstyled class on these elements if you need that styling that way.

Blockquote I’m not sure about whether we should remove – it’s quite a useful thing to have as it’s often used on sites.  Any reason in particular you wanted to scrap?

**Comment by mrmartineau** [comment]
Thanks @ashleynolan, I felt that the blockquote is not useful enough to keep. It is one of those things that would change on almost every project & not integral to the framework. I don't mind keeping it, just wanted to gauge opinions.

I'll remove the others.

**Comment by mrmartineau** [comment]
After thinking about it some more, I'd like to remove some more of the button styles:

## Large, Small, Pill, Block & Natural Buttons
I just don't think that they're used often enough. Perhaps the `.btn--block` could stay but I'm fairly certain the rest can be safely removed.

```scss 
// Button Modifiers
// --------------------------------------------------
// These all follow the same sizing rules as above; text is 1em, space around it
// Large
.btn--large {
	@include font-size($type-large);
	line-height: 3;
	height: 3em;
	padding-right: 2em;
	padding-left: 2em;
	border-radius: 6px;
}

// Small
.btn--small {
	@include font-size($type-small);
	line-height: 1.5;
	height: 1.5em;
	padding-right: .75em;
	padding-left: .75em;
	border-radius: 3px;
}

.btn--pill {
	padding-left: 1.5em;
	padding-right: 1.5em;
	border-radius: 100em;
}

// Block button
// -------------------------
.btn--block {
	display: block;
	width: 100%;
	padding-left: 0;
	padding-right: 0;

	// Vertically space out multiple block buttons
	// same ad .btn--block + .btn--block
	& + & {
		margin-top: 10px;
	}
}


// Specificity overrides
input[type="submit"],
input[type="reset"],
input[type="button"] {
	&.btn--block {
		width: 100%;
	}
}

// Make the button inherit sizing from its parent.
.btn--natural {
	vertical-align: baseline;
	font-size: inherit;
	line-height: inherit;
	height: auto;
	padding-right: .5em;
	padding-left: .5em;
}
```

What do you think?
